// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaSJmMz6UELjm2PcbXZJRbMkbd-V4413c',
    appId: '1:717672718438:web:aa86f7923f9d2ff75ecda7',
    messagingSenderId: '717672718438',
    projectId: 'whatsapp-97b8c',
    authDomain: 'whatsapp-97b8c.firebaseapp.com',
    storageBucket: 'whatsapp-97b8c.firebasestorage.app',
    measurementId: 'G-C1RYR1XVX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFPH6l4GHd2AkQErHEMnOc4d-PkZ6Ps8w',
    appId: '1:717672718438:android:6c4530ca32782d015ecda7',
    messagingSenderId: '717672718438',
    projectId: 'whatsapp-97b8c',
    storageBucket: 'whatsapp-97b8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa_5p_uT3DiUm_kg8UTVkpEJxvtdRuIWc',
    appId: '1:717672718438:ios:c686d5ae171287585ecda7',
    messagingSenderId: '717672718438',
    projectId: 'whatsapp-97b8c',
    storageBucket: 'whatsapp-97b8c.firebasestorage.app',
    androidClientId: '717672718438-1kmnb8nbo8uoqp3qmltrlhn83s70fff3.apps.googleusercontent.com',
    iosClientId: '717672718438-o622031biqkvjj1u6a9e3ie3lqu12msu.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa_5p_uT3DiUm_kg8UTVkpEJxvtdRuIWc',
    appId: '1:717672718438:ios:c686d5ae171287585ecda7',
    messagingSenderId: '717672718438',
    projectId: 'whatsapp-97b8c',
    storageBucket: 'whatsapp-97b8c.firebasestorage.app',
    androidClientId: '717672718438-1kmnb8nbo8uoqp3qmltrlhn83s70fff3.apps.googleusercontent.com',
    iosClientId: '717672718438-o622031biqkvjj1u6a9e3ie3lqu12msu.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaSJmMz6UELjm2PcbXZJRbMkbd-V4413c',
    appId: '1:717672718438:web:479103fc63740dfd5ecda7',
    messagingSenderId: '717672718438',
    projectId: 'whatsapp-97b8c',
    authDomain: 'whatsapp-97b8c.firebaseapp.com',
    storageBucket: 'whatsapp-97b8c.firebasestorage.app',
    measurementId: 'G-977SDYKR9Y',
  );
}
